language: java
jdk:
- oraclejdk8
before_install:
- if [ ! -d "$HOME/.m2/repository/com/destroystokyo" ]; then ./installPaper.sh 1.12 ; else echo "Not compiling Paper because it is already in our maven" ; fi
