# Language file (for translations)
language-file: lang-en.yml

# Enabled the update checker (does not actually download updates!)
update-checker: true

# When players teleport for any reason, unmount from any creature they are riding
"unmount-on-teleport": true

# While player is riding a creature, disable commands for them
"cancel-commands-while-riding": false

# Dolphin options
dolphin:
  speed: 1.0         # riding speed modifier
  bounce: true       # enable small up/down bouncing motion when still
  bubbles: true      # enable bubble trail when in motion
  spacebar: "shoot"  # valid options are "shoot" or "dash"
  shoot:
    cooldown: 10     # ticks to wait between shooting
    speed: 1.0       # projectile speed
    damage: 2.0      # damage per hit (1 heart = 2.0 damage)
  dash:
    cooldown: 100    # ticks to wait between dashing
    boost: 1.5       # riding speed multiplier boost
    duration: 20     # ticks boost lasts for with each spacebar press

# Turtle options
turtle:
  speed:
    on-land: 1.0     # riding speed modifier on land
    in-water: 1.0    # riding speed modifier in water

# Phantom options
phantom:
  speed: 1.0         # riding speed modifier
  gravity: 0.05      # amount of gravity while not in motion
  fall-damage: true  # damage if fall too quickly
  burn-in-sun: true  # burn in sunlight
  max-y: 256         # max Y height the phantom can be controlled to

# Polar bear options
polar-bear:
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  step-height: 0.6   # block height of step (1.0 means they can walk up 1 block like horses)
