# Language file (for translations)
language-file: lang-en.yml

# Debug mode. Enable this before reporting any issues, please
debug-mode: false

# Use the new WASD key yaw calculations
use-new-wasd-yaw-calculations: true

# Enabled the update checker (does not actually download updates!)
update-checker: true

# When players teleport for any reason, unmount from any creature they are riding
unmount-on-teleport: true

# While player is riding a creature, disable commands for them
cancel-commands-while-riding: false

# Require saddle in hand to mount a ridable creature
# Does not work for creatures that are naturally mountable
saddle-to-mount: false

# Consume the saddle item when mounting (requires saddle-to-mount: true)
consume-saddle: false

# Limit flying creatures to a max Y (prevents players from crashing servers from riding too high)
flying-max-y: 256

# Bat options
bat:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  vertical: 1.0      # vertical boost when pressing spacebar
  gravity: 0.04      # amount of gravity while not in motion

# Cave Spider options
cave-spider:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  climb-walls: true  # enable climbing walls
  climb-speed: 1.0   # speed of vertical climb

# Chicken options
chicken:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Cow options
cow:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Creeper options
creeper:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  explosion:
    damage: 5.0      # damage per hit (1 heart = 2.0 damage) set to negative value to let vanilla handle the damage modifier
    grief: true      # whether ghast fireballs can damage the blocks in the world

# Dolphin options
dolphin:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  bounce: true       # enable small up/down bouncing motion when still
  bubbles: true      # enable bubble trail when in motion
  spacebar: "shoot"  # valid options are "shoot" or "dash"
  shoot:
    cooldown: 10     # ticks to wait between shooting
    speed: 1.0       # projectile speed
    damage: 2.0      # damage per hit (1 heart = 2.0 damage)
  dash:
    cooldown: 100    # ticks to wait between dashing
    boost: 1.5       # riding speed multiplier boost
    duration: 20     # ticks boost lasts for with each spacebar press

# Ender Dragon options
dragon:
  enabled: false     # enable custom ridable entity
  speed: 1.0         # riding speed modifier

# Ghast options
ghast:
  enabled: false     # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  shoot:
    cooldown: 20     # ticks to wait between shooting
    speed: 1.0       # projectile speed
    damage: 5.0      # damage per hit (1 heart = 2.0 damage)
    grief: true      # whether ghast fireballs can damage the blocks in the world

# Iron Golem options
iron-golem:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Llama options
llama:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  caravan: true      # create caravan while riding llama

# Mooshroom (Mushroom Cow) options
mooshroom:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Ocelot options
ocelot:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Parrot options
parrot:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  vertical: 1.0      # vertical boost when pressing spacebar
  gravity: 0.04      # amount of gravity while not in motion

# Pig options
pig:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  saddle-back: true  # Get your saddle back by shift clicking the pig

# Phantom options
phantom:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  gravity: 0.05      # amount of gravity while not in motion
  fall-damage: true  # damage if fall too quickly
  burn-in-sun: true  # burn in sunlight
  shoot-damage: 1.0  # damage per hit (1 heart = 2.0 damage)

# Polar Bear options
polar-bear:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  step-height: 0.6   # block height of step (1.0 means they can walk up 1 block like horses)
  stand: true        # make polar bear stand and roar when pressing spacebar (while not moving)

# Rabbit options
rabbit:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Sheep options
sheep:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Snowman (Snow Golem) options
snowman:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  damage:
    when-hot: true   # snowman takes damage when wet (rain/water)
    when-wet: true   # snowman takes damage when too hot (hot biomes)
  snow-trail: true   # leave a snow layer on ground where snowman walks

# Spider options
spider:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
  climb-walls: true  # enable climbing walls
  climb-speed: 1.0   # speed of vertical climb

# Turtle options
turtle:
  enabled: true      # enable custom ridable entity
  speed:
    on-land: 1.0     # riding speed modifier on land
    in-water: 1.0    # riding speed modifier in water

# Wolf options
wolf:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)

# Villager options
villager:
  enabled: true      # enable custom ridable entity
  speed: 1.0         # riding speed modifier
  jump-power: 0.5    # jumping power (keep in mind they take fall damage)
