do-not-change-this: 2
language-file: lang-en.yml
logger:
  info: true
  warn: true
  error: true
  debug: false

# Commands allowed (or disallowed) to be used while riding a mob
commands-list-is-whitelist: true  # Use false for blacklist
commands-list:
- "whisper"
- "msg"
- "pm"

# Delete this section if you want to fine-tune these options per entity
riding:
  enable-move-event: false
  saddle:
    require: false
    consume: false

# Enable mobs here
mobs:
  bat: false
  blaze: false
  cave_spider: false
  chicken: false
  cod: false
  cow: false
  creeper: false
  dolphin: false
  donkey: false
  dragon: false
  drowned: false
  elder_guardian: false
  ender_dragon: false
  enderman: false
  endermite: false
  evoker: false
  ghast: false
  giant: false
  guardian: false
  horse: false
  husk: false
  illusioner: false
  iron_golem: false
  llama: false
  magma_cube: false
  mooshroom: false
  mule: false
  ocelot: false
  parrot: false
  pig: false
  phantom: false
  polar_bear: false
  pufferfish: false
  rabbit: false
  salmon: false
  sheep: false
  shulker: false
  silverfish: false
  skeleton: false
  skeleton_horse: false
  slime: false
  snow_golem: false
  spider: false
  squid: false
  stray: false
  tropical_fish: false
  turtle: false
  vex: false
  villager: false
  vindicator: false
  witch: false
  wither: false
  wither_skeleton: false
  wolf: false
  zombie: false
  zombie_horse: false
  zombie_pigman: false
  zombie_villager: false
