# Config format version (do not change this!)
config: 2

# Language file (for translations)
language-file: lang-en.yml

# Debug mode. Enable this before reporting any issues, please
debug-mode: false

# Hide the "spammy" startup console output about entity injectors
hide-startup-console-output: false

# Enabled the update checker (does NOT actually download updates!)
update-checker: true

# While player is riding a creature, disable all commands for them
cancel-commands-while-riding: false

# Commands allowed (or disallowed) to be used while riding a mob
commands-list-is-whitelist: true  # Use false for blacklist
commands-list:
- "whisper"
- "msg"
- "pm"

# Require saddle in hand to mount a ridable creature
# Does not work for creatures that are naturally mountable
saddle-to-mount: false

# Consume the saddle item when mounting (requires saddle-to-mount: true)
consume-saddle: false

# Can players ride baby versions of creatures
allow-ride-babies: false

# Limit flying creatures to a max Y (prevents players from crashing servers from riding too high)
flying-max-y: 256

# Enable mobs here
mobs:
  bat: false
  blaze: false
  cave_spider: false
  chicken: false
  cod: false
  cow: false
  creeper: false
  dolphin: false
  donkey: false
  dragon: false
  drowned: false
  elder_guardian: false
  ender_dragon: false
  enderman: false
  endermite: false
  evoker: false
  ghast: false
  giant: false
  guardian: false
  horse: false
  husk: false
  illusioner: false
  iron_golem: false
  llama: false
  magma_cube: false
  mooshroom: false
  mule: false
  ocelot: false
  parrot: false
  pig: false
  phantom: false
  polar_bear: false
  pufferfish: false
  rabbit: false
  salmon: false
  sheep: false
  shulker: false
  silverfish: false
  skeleton: false
  skeleton_horse: false
  slime: false
  snow_golem: false
  spider: false
  squid: false
  stray: false
  tropical_fish: false
  turtle: false
  vex: false
  villager: false
  vindicator: false
  witch: false
  wither: false
  wither_skeleton: false
  wolf: false
  zombie: false
  zombie_horse: false
  zombie_pigman: false
  zombie_villager: false
