name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} CraftBukkit/Spigot/Paper Plugin"
author: "BillyGalbreath"
api-version: 1.13

commands:
  ridables:
    description: Reload config
    usage: /<command> reload
    aliases:
    - rideables
    - rideable
    - ridable

permissions:
  allow.collect.*:
    description: Allow to collect all supported creatures in water buckets
    default: op
    children:
      allow.collect.dolphin:
        description: Allow to collect dolphins in water buckets
        default: op
      allow.collect.turtle:
        description: Allow to collect turtles in water buckets
        default: op
  allow.dash.*:
    description: Allow to make all supported creatures dash
    default: op
    children:
      allow.dash.dolphin:
        description: Allow to make dolphins dash
        default: op
  allow.ride.*:
    description: Allow to ride all supported creatures
    default: op
    children:
      allow.ride.bat:
        description: Allow to ride bats
        default: op
      allow.ride.cave_spider:
        description: Allow to ride cave spiders
        default: op
      allow.ride.chicken:
        description: Allow to ride chickens
        default: op
      allow.ride.cow:
        description: Allow to ride cows
        default: op
      allow.ride.creeper:
        description: Allow to ride creepers
        default: op
      allow.ride.dolphin:
        description: Allow to ride dolphins
        default: op
      allow.ride.drowned:
        description: Allow to ride drowned
        default: op
      allow.ride.ender_dragon:
        description: Allow to ride ender dragon
        default: op
      allow.ride.enderman:
        description: Allow to ride endermen
        default: op
      allow.ride.endermite:
        description: Allow to ride endermites
        default: op
      allow.ride.evoker:
        description: Allow to ride evokers
        default: op
      allow.ride.ghast:
        description: Allow to ride ghast
        default: op
      allow.ride.husk:
        description: Allow to ride husks
        default: op
      allow.ride.illusioner:
        description: Allow to ride illusioners
        default: op
      allow.ride.iron_golem:
        description: Allow to ride iron golems
        default: op
      allow.ride.llama:
        description: Allow to ride llamas
        default: op
      allow.ride.mooshroom:
        description: Allow to ride mooshrooms
        default: op
      allow.ride.ocelot:
        description: Allow to ride tamed ocelots
        default: op
      allow.ride.parrot:
        description: Allow to ride parrots
        default: op
      allow.ride.phantom:
        description: Allow to ride phantoms
        default: op
      allow.ride.pig:
        description: Allow to ride pigs
        default: op
      allow.ride.polar_bear:
        description: Allow to ride polar bears
        default: op
      allow.ride.rabbit:
        description: Allow to ride rabbits
        default: op
      allow.ride.sheep:
        description: Allow to ride sheep
        default: op
      allow.ride.skeleton:
        description: Allow to ride skeletons
        default: op
      allow.ride.snowman:
        description: Allow to ride snowman
        default: op
      allow.ride.spider:
        description: Allow to ride spiders
        default: op
      allow.ride.stray:
        description: Allow to ride strays
        default: op
      allow.ride.turtle:
        description: Allow to ride turtles
        default: op
      allow.ride.villager:
        description: Allow to ride villagers
        default: op
      allow.ride.vindicator:
        description: Allow to ride vindicators
        default: op
      allow.ride.wolf:
        description: Allow to ride tamed wolves
        default: op
      allow.ride.zombie:
        description: Allow to ride zombies
        default: op
      allow.ride.zombie_pigman:
        description: Allow to ride zombie pigman
        default: op
      allow.ride.zombie_villager:
        description: Allow to ride zombie villagers
        default: op
  allow.shoot.*:
    description: Allow to make all supported creatures shoot
    default: op
    children:
      allow.shoot.dolphin:
        description: Allow to make dolphins shoot spit
        default: op
      allow.shoot.ghast:
        description: Allow to make ghasts shoot fireballs
        default: op
      allow.shoot.phantom:
        description: Allow to make phantoms shoot flames
        default: op
  allow.special.*:
    description: Allow to make all supported creatures do their special
    default: op
    children:
      allow.special.creeper:
        description: Allow to make creepers ignite
        default: op
      allow.special.enderman:
        description: Allow to make endermen pick up and place blocks
        default: op
  command.ridables:
    description: Allow to reload config
    default: op
