name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} CraftBukkit/Spigot/Paper Plugin"
author: "BillyGalbreath"
api-version: 1.13

commands:
  ridables:
    description: Reload config
    usage: /<command> reload
    aliases:
    - rideables
    - rideable
    - ridable

permissions:
  allow.collect.*:
    description: Allow to collect all supported creatures in water buckets
    default: op
    children:
      allow.collect.dolphin:
        description: Allow to collect dolphins in water buckets
        default: op
      allow.collect.turtle:
        description: Allow to collect turtles in water buckets
        default: op
  allow.ride.*:
    description: Allow to ride all supported creatures
    default: op
    children:
      allow.ride.bat:
        description: Allow to ride bats
        default: op
      allow.ride.blaze:
        description: Allow to ride blazes
        default: op
      allow.ride.cave_spider:
        description: Allow to ride cave spiders
        default: op
      allow.ride.chicken:
        description: Allow to ride chickens
        default: op
      allow.ride.cod:
        description: Allow to ride cod fish
        default: op
      allow.ride.cow:
        description: Allow to ride cows
        default: op
      allow.ride.creeper:
        description: Allow to ride creepers
        default: op
      allow.ride.dolphin:
        description: Allow to ride dolphins
        default: op
      allow.ride.drowned:
        description: Allow to ride drowned
        default: op
      allow.ride.elder_guardian:
        description: Allow to ride elder guardians
        default: op
      allow.ride.ender_dragon:
        description: Allow to ride ender dragon
        default: op
      allow.ride.enderman:
        description: Allow to ride endermen
        default: op
      allow.ride.endermite:
        description: Allow to ride endermites
        default: op
      allow.ride.evoker:
        description: Allow to ride evokers
        default: op
      allow.ride.ghast:
        description: Allow to ride ghast
        default: op
      allow.ride.giant:
        description: Allow to ride giants
        default: op
      allow.ride.guardian:
        description: Allow to ride guardians
        default: op
      allow.ride.husk:
        description: Allow to ride husks
        default: op
      allow.ride.illusioner:
        description: Allow to ride illusioners
        default: op
      allow.ride.iron_golem:
        description: Allow to ride iron golems
        default: op
      allow.ride.llama:
        description: Allow to ride llamas
        default: op
      allow.ride.magma_cube:
        description: Allow to ride magma cubes
        default: op
      allow.ride.mooshroom:
        description: Allow to ride mooshrooms
        default: op
      allow.ride.ocelot:
        description: Allow to ride tamed ocelots
        default: op
      allow.ride.parrot:
        description: Allow to ride parrots
        default: op
      allow.ride.phantom:
        description: Allow to ride phantoms
        default: op
      allow.ride.pig:
        description: Allow to ride pigs
        default: op
      allow.ride.polar_bear:
        description: Allow to ride polar bears
        default: op
      allow.ride.pufferfish:
        description: Allow to ride pufferfish
        default: op
      allow.ride.rabbit:
        description: Allow to ride rabbits
        default: op
      allow.ride.salmon:
        description: Allow to ride salmon
        default: op
      allow.ride.sheep:
        description: Allow to ride sheep
        default: op
      allow.ride.shulker:
        description: Allow to ride shulkers
        default: op
      allow.ride.silverfish:
        description: Allow to ride silverfish
        default: op
      allow.ride.skeleton:
        description: Allow to ride skeletons
        default: op
      allow.ride.skeleton_horse:
        description: Allow to ride skeleton horses
        default: op
      allow.ride.slime:
        description: Allow to ride slimes
        default: op
      allow.ride.snow_golem:
        description: Allow to ride snowman
        default: op
      allow.ride.spider:
        description: Allow to ride spiders
        default: op
      allow.ride.squid:
        description: Allow to ride squids
        default: op
      allow.ride.stray:
        description: Allow to ride strays
        default: op
      allow.ride.tropical_fish:
        description: Allow to ride tropical fish
        default: op
      allow.ride.turtle:
        description: Allow to ride turtles
        default: op
      allow.ride.vex:
        description: Allow to ride vex
        default: op
      allow.ride.villager:
        description: Allow to ride villagers
        default: op
      allow.ride.vindicator:
        description: Allow to ride vindicators
        default: op
      allow.ride.witch:
        description: Allow to ride witches
        default: op
      allow.ride.wither:
        description: Allow to ride withers
        default: op
      allow.ride.wither_skeleton:
        description: Allow to ride wither skeletons
        default: op
      allow.ride.wolf:
        description: Allow to ride tamed wolves
        default: op
      allow.ride.zombie:
        description: Allow to ride zombies
        default: op
      allow.ride.zombie_horse:
        description: Allow to ride zombie horses
        default: op
      allow.ride.zombie_pigman:
        description: Allow to ride zombie pigman
        default: op
      allow.ride.zombie_villager:
        description: Allow to ride zombie villagers
        default: op
  allow.shoot.*:
    description: Allow to make all supported creatures shoot
    default: op
    children:
      allow.shoot.blaze:
        description: Allow to make blazes shoot fireballs
        default: op
      allow.shoot.dolphin:
        description: Allow to make dolphins shoot spit
        default: op
      allow.shoot.drowned:
        description: Allow to make drownedd throw tridents
        default: op
      allow.shoot.ghast:
        description: Allow to make ghasts shoot fireballs
        default: op
      allow.shoot.phantom:
        description: Allow to make phantoms shoot flames
        default: op
      allow.shoot.shulker:
        description: Allow to make withers shoot shulker bullets
        default: op
      allow.shoot.wither:
        description: Allow to make withers shoot skulls
        default: op
  allow.special.*:
    description: Allow to make all supported creatures do their special
    default: op
    children:
      allow.special.creeper:
        description: Allow to make creepers ignite
        default: op
      allow.special.dolphin:
        description: Allow to make dolphins dash
        default: op
      allow.special.enderman:
        description: Allow to make endermen pick up and place blocks
        default: op
      allow.special.evoker:
        description: Allow to make evokers cast fangs spell
        default: op
  allow.teleport.*:
    description: Allow to teleport with all supported creatures
    default: op
    children:
      allow.teleport.bat:
        description: Allow to teleport with bats
        default: op
      allow.teleport.blaze:
        description: Allow to teleport with blazes
        default: op
      allow.teleport.cave_spider:
        description: Allow to teleport with cave spiders
        default: op
      allow.teleport.chicken:
        description: Allow to teleport with chickens
        default: op
      allow.teleport.cod:
        description: Allow to teleport with cod fish
        default: op
      allow.teleport.cow:
        description: Allow to teleport with cows
        default: op
      allow.teleport.creeper:
        description: Allow to teleport with creepers
        default: op
      allow.teleport.dolphin:
        description: Allow to teleport with dolphins
        default: op
      allow.teleport.drowned:
        description: Allow to teleport with drowned
        default: op
      allow.teleport.elder_guardian:
        description: Allow to teleport with elder guardians
        default: op
      allow.teleport.ender_dragon:
        description: Allow to teleport with ender dragon
        default: op
      allow.teleport.enderman:
        description: Allow to teleport with endermen
        default: op
      allow.teleport.endermite:
        description: Allow to teleport with endermites
        default: op
      allow.teleport.evoker:
        description: Allow to teleport with evokers
        default: op
      allow.teleport.ghast:
        description: Allow to teleport with ghast
        default: op
      allow.teleport.giant:
        description: Allow to teleport with giants
        default: op
      allow.teleport.guardian:
        description: Allow to teleport with guardians
        default: op
      allow.teleport.husk:
        description: Allow to teleport with husks
        default: op
      allow.teleport.illusioner:
        description: Allow to teleport with illusioners
        default: op
      allow.teleport.iron_golem:
        description: Allow to teleport with iron golems
        default: op
      allow.teleport.llama:
        description: Allow to teleport with llamas
        default: op
      allow.teleport.magma_cube:
        description: Allow to teleport with magma cubes
        default: op
      allow.teleport.mooshroom:
        description: Allow to teleport with mooshrooms
        default: op
      allow.teleport.ocelot:
        description: Allow to teleport with tamed ocelots
        default: op
      allow.teleport.parrot:
        description: Allow to teleport with parrots
        default: op
      allow.teleport.phantom:
        description: Allow to teleport with phantoms
        default: op
      allow.teleport.pig:
        description: Allow to teleport with pigs
        default: op
      allow.teleport.polar_bear:
        description: Allow to teleport with polar bears
        default: op
      allow.teleport.pufferfish:
        description: Allow to teleport with pufferfish
        default: op
      allow.teleport.rabbit:
        description: Allow to teleport with rabbits
        default: op
      allow.teleport.salmon:
        description: Allow to teleport with salmon
        default: op
      allow.teleport.sheep:
        description: Allow to teleport with sheep
        default: op
      allow.teleport.shulker:
        description: Allow to teleport with shulkers
        default: op
      allow.teleport.silverfish:
        description: Allow to teleport with silverfish
        default: op
      allow.teleport.skeleton:
        description: Allow to teleport with skeletons
        default: op
      allow.teleport.skeleton_horse:
        description: Allow to teleport with skeleton horses
        default: op
      allow.teleport.slime:
        description: Allow to teleport with slimes
        default: op
      allow.teleport.snow_golem:
        description: Allow to teleport with snowman
        default: op
      allow.teleport.spider:
        description: Allow to teleport with spiders
        default: op
      allow.teleport.squid:
        description: Allow to teleport with squids
        default: op
      allow.teleport.stray:
        description: Allow to teleport with strays
        default: op
      allow.teleport.tropical_fish:
        description: Allow to teleport with tropical fish
        default: op
      allow.teleport.turtle:
        description: Allow to teleport with turtles
        default: op
      allow.teleport.vex:
        description: Allow to teleport with vex
        default: op
      allow.teleport.villager:
        description: Allow to teleport with villagers
        default: op
      allow.teleport.vindicator:
        description: Allow to teleport with vindicators
        default: op
      allow.teleport.witch:
        description: Allow to teleport with witches
        default: op
      allow.teleport.wither:
        description: Allow to teleport with withers
        default: op
      allow.teleport.wither_skeleton:
        description: Allow to teleport with wither skeletons
        default: op
      allow.teleport.wolf:
        description: Allow to teleport with tamed wolves
        default: op
      allow.teleport.zombie:
        description: Allow to teleport with zombies
        default: op
      allow.teleport.zombie_horse:
        description: Allow to teleport with zombie horses
        default: op
      allow.teleport.zombie_pigman:
        description: Allow to teleport with zombie pigman
        default: op
      allow.teleport.zombie_villager:
        description: Allow to teleport with zombie villagers
        default: op
  command.ridables:
    description: Allow to reload config
    default: op
