name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Spigot/Paper Plugin
author: BillyGalbreath
api-version: 1.13

commands:
  ridables:
    description: Reload config
    usage: /<command> reload
    aliases:
    - rideables
    - rideable
    - ridable

permissions:
  allow.collect.*:
    description: Allow to collect all supported creatures in water buckets
    default: op
    children:
      allow.collect.dolphin:
        description: Allow to collect dolphins in water buckets
        default: op
      allow.collect.turtle:
        description: Allow to collect turtles in water buckets
        default: op
  allow.dash.*:
    description: Allow to make all supported creatures dash
    default: op
    children:
      allow.dash.dolphin:
        description: Allow to make dolphins dash
        default: op
  allow.ride.*:
    description: Allow to ride all supported creatures
    default: op
    children:
      allow.ride.chicken:
        description: Allow to ride chickens
        default: op
      allow.ride.cow:
        description: Allow to ride cows
        default: op
      allow.ride.dolphin:
        description: Allow to ride dolphins
        default: op
      allow.ride.ender_dragon:
        description: Allow to ride ender dragon
        default: op
      allow.ride.llama:
        description: Allow to ride llamas
        default: op
      allow.ride.ocelot:
        description: Allow to ride tamed ocelots
        default: op
      allow.ride.phantom:
        description: Allow to ride phantoms
        default: op
      allow.ride.polar_bear:
        description: Allow to ride polar bears
        default: op
      allow.ride.turtle:
        description: Allow to ride turtles
        default: op
      allow.ride.wolf:
        description: Allow to ride tamed wolves
        default: op
  allow.shoot.*:
    description: Allow to make all supported creatures shoot
    default: op
    children:
      allow.shoot.dolphin:
        description: Allow to make dolphins shoot spit
        default: op
  command.ridables:
    description: Allow to reload config
    default: op
